"""
Contain all the configuration of the IDS 

This configuration file should not be changeable
"""

db_file = "./ids/incoming_packets.csv"
sleep_time = 0.01

drop_duplicates = True # Whether or not duplicate in the dataset should be removed
convert_labels = True # Convert all normal trafic to 0 and all atacks to 1
oversample = False # Whether or not oversample should be used in the dataset
# List all datasets
datasets_names = ["kdd99", "cic-ids-2017"]

features = {
    "kdd99": {
        "features": {
            "duration": "continuous",
            "protocol_type": "symbolic",
            "service": "symbolic",
            "flag": "symbolic",
            "src_bytes": "continuous",
            "dst_bytes": "continuous",
            "land": "symbolic",
            "wrong_fragment": "continuous",
            "urgent": "continuous",
            "hot": "continuous",
            "num_failed_logins": "continuous",
            "logged_in": "symbolic",
            "num_compromised": "continuous",
            "root_shell": "continuous",
            "su_attempted": "continuous",
            "num_root": "continuous",
            "num_file_creations": "continuous",
            "num_shells": "continuous",
            "num_access_files": "continuous",
            "num_outbound_cmds": "continuous",
            "is_host_login": "symbolic",
            "is_guest_login": "symbolic",
            "count": "continuous",
            "srv_count": "continuous",
            "serror_rate": "continuous",
            "srv_serror_rate": "continuous",
            "rerror_rate": "continuous",
            "srv_rerror_rate": "continuous",
            "same_srv_rate": "continuous",
            "diff_srv_rate": "continuous",
            "srv_diff_host_rate": "continuous",
            "dst_host_count": "continuous",
            "dst_host_srv_count": "continuous",
            "dst_host_same_srv_rate": "continuous",
            "dst_host_diff_srv_rate": "continuous",
            "dst_host_same_src_port_rate": "continuous",
            "dst_host_srv_diff_host_rate": "continuous",
            "dst_host_serror_rate": "continuous",
            "dst_host_srv_serror_rate": "continuous",
            "dst_host_rerror_rate": "continuous",
            "dst_host_srv_rerror_rate": "continuous",
            "label" : "symbolic"
        },
        "normal_traffic" : "normal",
        "filename": "training70_kddcup.data_10_percent_corrected"
    },
    "unsw_nb15": {
        "features": {
            "srcip": "nominal",
            "sport": "integer",
            "dstip": "nominal",
            "dsport": "integer",
            "proto": "nominal",
            "state": "nominal",
            "dur": "Float",
            "sbytes": "Integer",
            "dbytes": "Integer",
            "sttl": "Integer",
            "dttl": "Integer",
            "sloss": "Integer",
            "dloss": "Integer",
            "service": "nominal",
            "Sload": "Float",
            "Dload": "Float",
            "Spkts": "integer",
            "Dpkts": "integer",
            "swin": "integer",
            "dwin": "integer",
            "stcpb": "integer",
            "dtcpb": "integer",
            "smeansz": "integer",
            "dmeansz": "integer",
            "trans_depth": "integer",
            "res_bdy_len": "integer",
            "Sjit": "Float",
            "Djit": "Float",
            "Stime": "Timestamp",
            "Ltime": "Timestamp",
            "Sintpkt": "Float",
            "Dintpkt": "Float",
            "tcprtt": "Float",
            "synack": "Float",
            "ackdat": "Float",
            "is_sm_ips_ports": "Binary",
            "ct_state_ttl": "Integer",
            "ct_flw_http_mthd": "Integer",
            "is_ftp_login": "Binary",
            "ct_ftp_cmd": "integer",
            "ct_srv_src": "integer",
            "ct_srv_dst": "integer",
            "ct_dst_ltm": "integer",
            "ct_src__ltm":	"integer",
            "ct_src_dport_ltm" : "integer",
            "ct_dst_sport_ltm": "integer",
            "ct_dst_src_ltm": "integer",
            "attack_cat": "nominal",
            "label": "binary"
        },
        "normal_traffic": "0",
        "filename": "UNSW_NB15_training-set.csv"
    },
    "cic-ids-2017": {
        "features": {
            "Destination Port": "continuous",
            "Flow Duration": "continuous",
            "Total Fwd Packets": "continuous",
            "Total Backward Packets": "continuous",
            "Total Length of Fwd Packets": "continuous",
            "Total Length of Bwd Packets": "continuous",
            "Fwd Packet Length Max": "continuous",
            "Fwd Packet Length Min": "continuous",
            "Fwd Packet Length Mean": "continuous",
            "Fwd Packet Length Std": "continuous",
            "Bwd Packet Length Max": "continuous",
            "Bwd Packet Length Min": "continuous",
            "Bwd Packet Length Mean": "continuous",
            "Bwd Packet Length Std": "continuous",
            "Flow Bytes/s": "continuous",
            "Flow Packets/s": "continuous",
            "Flow IAT Mean": "continuous",
            "Flow IAT Std": "continuous",
            "Flow IAT Max": "continuous",
            "Flow IAT Min": "continuous",
            "Fwd IAT Total": "continuous",
            "Fwd IAT Mean": "continuous",
            "Fwd IAT Std": "continuous",
            "Fwd IAT Max": "continuous",
            "Fwd IAT Min": "continuous",
            "Bwd IAT Total": "continuous",
            "Bwd IAT Mean": "continuous",
            "Bwd IAT Std": "continuous",
            "Bwd IAT Max": "continuous",
            "Bwd IAT Min": "continuous",
            "Fwd PSH Flags": "continuous",
            "Bwd PSH Flags": "continuous",
            "Fwd URG Flags": "continuous",
            "Bwd URG Flags": "continuous",
            "Fwd Header Length": "continuous",
            "Bwd Header Length": "continuous",
            "Fwd Packets/s": "continuous",
            "Bwd Packets/s": "continuous",
            "Min Packet Length": "continuous",
            "Max Packet Length": "continuous",
            "Packet Length Mean": "continuous",
            "Packet Length Std": "continuous",
            "Packet Length Variance": "continuous",
            "FIN Flag Count": "continuous",
            "SYN Flag Count": "continuous",
            "RST Flag Count": "continuous",
            "PSH Flag Count": "continuous",
            "ACK Flag Count": "continuous",
            "URG Flag Count": "continuous",
            "CWE Flag Count": "continuous",
            "ECE Flag Count": "continuous",
            "Down/Up Ratio": "continuous",
            "Average Packet Size": "continuous",
            "Avg Fwd Segment Size": "continuous",
            "Avg Bwd Segment Size": "continuous",
            "Fwd Avg Bytes/Bulk": "continuous",
            "Fwd Avg Packets/Bulk": "continuous",
            "Fwd Avg Bulk Rate": "continuous",
            "Bwd Avg Bytes/Bulk": "continuous",
            "Bwd Avg Packets/Bulk": "continuous",
            "Bwd Avg Bulk Rate": "continuous",
            "Subflow Fwd Packets": "continuous",
            "Subflow Fwd Bytes": "continuous",
            "Subflow Bwd Packets": "continuous",
            "Subflow Bwd Bytes": "continuous",
            "Init_Win_bytes_forward": "continuous",
            "Init_Win_bytes_backward": "continuous",
            "act_data_pkt_fwd": "continuous",
            "min_seg_size_forward": "continuous",
            "Active Mean": "continuous",
            "Active Std": "continuous",
            "Active Max": "continuous",
            "Active Min": "continuous",
            "Idle Mean": "continuous",
            "Idle Std": "continuous",
            "Idle Max": "continuous",
            "Idle Min": "continuous",
            "label": "symbolic"
        },
        "normal_traffic": "BENIGN",
        "filename": "training70_cic-ids.csv"
    }
}
